# -*- coding: utf-8 -*-
"""A3-inclass.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QDoNhAZedwiwYOFXFr6Xxn_dUwHRLH2W
"""

# This is the problem:
# SHA256("CPEN 442 Coin" + "2022" + hash_of_preceding_coin + coin_blob + id_of_miner)
#           ^ constant      ^ constant    ^ given             ^ find it.    ^ we choose.
# Success if output starts with '0000'
import hashlib
import time
a_string = 'this string holds important and private information'
hashed_string = hashlib.sha256(a_string.encode('utf-8')).hexdigest()
print(hashed_string)

# This is given.
hash_of_preceding_coin = "a9c1ae3f4fc29d0be9113a42090a5ef9fdef93f5ec4777a008873972e60bb532"
# We choose this one.
id_of_miner = "256"
# coin_blob <-- we need to iterate on this one.
print("About to Run BIG LOOP")

# --- 1. for 4 zero's: 0000
tic = time.perf_counter()
for coin_blob in range(0, 0X7FFFFFFF):
  # Concatenate them.
  a_string = "CPEN 442 Coin" + "2022" + hash_of_preceding_coin + str(coin_blob) + id_of_miner
  hashed_string = hashlib.sha256(a_string.encode('utf-8')).hexdigest()
  if hashed_string[0:4] == '0000':
    print("Success!")
    print(hashed_string)
    print("coin blob: " + str(coin_blob))
    break;
toc = time.perf_counter()
print("DONE")
print(f"Solved 4 zeros in {toc - tic:0.4f} seconds.")

# --- 2. for 5 zero's: 00000 --------
tic = time.perf_counter()
for coin_blob in range(0, 0X7FFFFFFF):
  # Concatenate them.
  a_string = "CPEN 442 Coin" + "2022" + hash_of_preceding_coin + str(coin_blob) + id_of_miner
  hashed_string = hashlib.sha256(a_string.encode('utf-8')).hexdigest()
  if hashed_string[0:5] == '00000':
    print("Success!")
    print(hashed_string)
    print("coin blob: " + str(coin_blob))
    break;
toc = time.perf_counter()
print("DONE")
print(f"Solved 5 zeros in {toc - tic:0.4f} seconds.")


# --- 3. for 6 zero's: 000000 ---------
#https://realpython.com/python-timer/
tic = time.perf_counter()
for coin_blob in range(0, 0X7FFFFFFF):
  # Concatenate them.
  a_string = "CPEN 442 Coin" + "2022" + hash_of_preceding_coin + str(coin_blob) + id_of_miner
  hashed_string = hashlib.sha256(a_string.encode('utf-8')).hexdigest()
  if hashed_string[0:6] == '000000':
    print("Success!")
    print(hashed_string)
    print("coin blob: " + str(coin_blob))
    break;
toc = time.perf_counter()
print("DONE")
print(f"Solved 6 zeros in {toc - tic:0.4f} seconds.")

# References; https://datagy.io/python-sha256/ -- gives the has function, converts it to string.